export const token =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJsYXVyYWRvbmRpZWdvQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoibGF1cmFkZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTU3MjM3NjkxMCwiZXhwIjoxNTcyMzc4NzEwfQ.ZgwVnqLDLSkMoJPoH2oQ7lAwGT_qFQH9-lmxBQ0crHA'
