
export const token =  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJza3lsZXIyNDQwQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoic2t5bGVyZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTU3MjMwNjk2OSwiZXhwIjoxNTcyMzA4NzY5fQ.xsBSGfr7hfe_mUqBPzpPeFsJDrX3S_nzLU4I5Ke4Jbo"
