export const types = {
  //AUTH USER TYPES//
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',

  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'LOGOUT_FAIL',

  CREATE_USER_START: 'CREATE_USER_START',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAIL: 'CREATE_USER_FAIL',

  GET_USER_START: 'GET_USER_START',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAIL: 'GET_USER_FAIL',

  UPDATE_USER_START: 'UPDATE_USER_START',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',

  DELETE_USER_START: 'DELETE_USER_START',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAIL: 'DELETE_USER_FAIL',

  CREATE_PROFILE_START: 'CREATE_PROFILE_START',
  CREATE_PROFILE_SUCCESS: 'CREATE_PROFILE_SUCCESS',
  CREATE_PROFILE_FAIL: 'CREATE_PROFILE_FAIL',

  GET_PROFILE_START: 'GET_PROFILE_START',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAIL: 'GET_PROFILE_FAIL',

  UPDATE_PROFILE_START: 'UPDATE_PROFILE_START',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL',

  DELETE_PROFILE_START: 'DELETE_PROFILE_START',
  DELETE_PROFILE_SUCCESS: 'DELETE_PROFILE_SUCCESS',
  DELETE_PROFILE_FAIL: 'DELETE_PROFILE_FAIL',
  //END AUTH USER TYPES//

  //UPLOAD//
  UPLOAD_START: 'UPLOAD_START',
  UPLOAD_SUCCESS: 'UPLOAD_SUCCESS',
  UPLOAD_FAIL: 'UPLOAD_FAIL',
  //END UPLOAD//

  //CRUD//

  CREATE__START: 'CREATE__START',
  CREATE__SUCCESS: 'CREATE__SUCCESS',
  CREATE__FAIL: 'CREATE__FAIL',

  GET__START: 'GET__START',
  GET__SUCCESS: 'GET__SUCCESS',
  GET__FAIL: 'GET__FAIL',

  UPDATE__START: 'UPDATE__START',
  UPDATE__SUCCESS: 'UPDATE__SUCCESS',
  UPDATE__FAIL: 'UPDATE__FAIL',

  DELETE__START: 'DELETE__START',
  DELETE__SUCCESS: 'DELETE__SUCCESS',
  DELETE__FAIL: 'DELETE__FAIL',

};
